/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportSentRouteImport } from './routes/report-sent'
import { Route as PreExamRouteImport } from './routes/pre-exam'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ClinicsRouteImport } from './routes/clinics'
import { Route as IndexRouteImport } from './routes/index'

const ReportSentRoute = ReportSentRouteImport.update({
  id: '/report-sent',
  path: '/report-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const PreExamRoute = PreExamRouteImport.update({
  id: '/pre-exam',
  path: '/pre-exam',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsRoute = ClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinics': typeof ClinicsRoute
  '/demo': typeof DemoRoute
  '/pre-exam': typeof PreExamRoute
  '/report-sent': typeof ReportSentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinics': typeof ClinicsRoute
  '/demo': typeof DemoRoute
  '/pre-exam': typeof PreExamRoute
  '/report-sent': typeof ReportSentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinics': typeof ClinicsRoute
  '/demo': typeof DemoRoute
  '/pre-exam': typeof PreExamRoute
  '/report-sent': typeof ReportSentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clinics' | '/demo' | '/pre-exam' | '/report-sent'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clinics' | '/demo' | '/pre-exam' | '/report-sent'
  id: '__root__' | '/' | '/clinics' | '/demo' | '/pre-exam' | '/report-sent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClinicsRoute: typeof ClinicsRoute
  DemoRoute: typeof DemoRoute
  PreExamRoute: typeof PreExamRoute
  ReportSentRoute: typeof ReportSentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report-sent': {
      id: '/report-sent'
      path: '/report-sent'
      fullPath: '/report-sent'
      preLoaderRoute: typeof ReportSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-exam': {
      id: '/pre-exam'
      path: '/pre-exam'
      fullPath: '/pre-exam'
      preLoaderRoute: typeof PreExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics': {
      id: '/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof ClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClinicsRoute: ClinicsRoute,
  DemoRoute: DemoRoute,
  PreExamRoute: PreExamRoute,
  ReportSentRoute: ReportSentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
